name: Deploy Starlight

on:
  push:
    branches:
      - starlight-main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Astro/Starlight site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: st-page